---
name: Search-and-Tweet

on:
  schedule:
    - cron: "* 1 * * *"
jobs:
  search-and-tweet:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🐍 Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: jupyter-actions
          environment-file: environment.yml
          python-version: 3.8
      - name: Execute notebook
        shell: bash -l {0}
        run: |
          conda activate jupyter-actions
          jupyter nbconvert --execute --clear-output --ExecutePreprocessor.kernel_name=python3 notebooks/retrieve.ipynb
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Nicolas Mondon
          author_email: nicolasmondon@gmail.com
          message: "Update [action]"
          add: "notebooks/ris.csv"
