---
name: Search-and-Tweet
on:
  #push:
  #  branches:
  #    - master
  schedule:
    - cron: "0 */8 * * *"
jobs:
  search-and-tweet:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🐍 Install python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
        run: pip install -r requirements.txt
      - name: Execute python script for assemblée nationale
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_KEY: ${{ secrets.TWITTER_ACCESS_KEY }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python notebooks/assemblee.py
      - name: Execute python script for sénat
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_KEY: ${{ secrets.TWITTER_ACCESS_KEY }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python notebooks/senat.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Nicolas Mondon
          author_email: nicolasmondon@gmail.com
          message: "Update [action]"
          add: "notebooks data"
